default_platform(:ios)

platform :ios do

  desc "Run unit tests"
  lane :test_unit do
    scan(scheme: "ReferenceiOS")
  end

  desc "Run UI tests"
  lane :test_ui do
    scan(scheme: "ReferenceiOSUITests")
  end
end
